# Generated by Django 5.2.7 on 2025-10-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client'), ('both', 'Both')], default='customer', max_length=20),
        ),
    ]
